easy_admin:
    site_name: 'Product Mini Manager'
    entities:
        Product:
            class: App\Entity\Product
            new:
                fields:
                  - { property : name , label: 'product.name' }
                  - { property: imageFile, label: 'product.image', type: 'vich_image' }
                  - { property : description , label: 'product.description', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType'}
                  - { property : price , label: 'product.price' }
            edit:
                fields:
                  - { property : name , label: 'product.name' }
                  - { property: imageFile, label: 'product.image', type: 'vich_image' }
                  - { property : description , label: 'product.description', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType'}
                  - { property : price , label: 'product.price' }
            list:
                max_results: 10
                fields:
                  - { property : id , label: 'product.id' }
                  - { property: imageName, label: 'product.image', type: 'image', base_path: '%path.product_images%'}
                  - { property : name , label: 'product.name' }
                  - { property : price , label: 'product.price' }
    design:
        templates:
            layout: 'override/admin_layout.html.twig'