version: '3'

services:
  product-man:
    container_name: product-manager-srv
    build:
      context: .
      dockerfile: docker/dockerfile-server
      args:
        VIRTUAL_HOST: 'product.manager.sf'
    volumes:
      - ./:/var/www/html
