version: '3'

services:
  product-man:
    container_name: product-manager-srv
    build:
      context: .
      dockerfile: docker/dockerfile-server
      args:
        VIRTUAL_HOST: 'product.manager.sf' #To add to your hosts with container-ip

    volumes:
      - ./:/var/www/html
    links:
      - sqlite

  sqlite:
    container_name: product-manager-db
    build:
      context: docker
      dockerfile: dockerfile-sqlite
